language: python

python: 3.6

dist: xenial

services:
  - docker

stages:
  - name: test
  - name: deploy
    if: tag IS present

install:
  - pip install tox-travis
  # overwrite default imagemagick policy that prevents reading PDF
  - sudo cp tests/travis-imagemagick-policy.xml /etc/ImageMagick-6/policy.xml
  - sudo apt-get -y install -f ghostscript
  # install wkhtmltopdf for native test
  - wget -q -O /tmp/wkhtmltox.deb https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
  - sudo apt -y install -f /tmp/wkhtmltox.deb
  # build and start server image
  - docker build -f Dockerfile-${WKHTMLTOPDF_VERSION} -t kwkhtmltopdf:${WKHTMLTOPDF_VERSION} .
  - docker run -d --name kwkhtmltopdf -p 8080:8080 kwkhtmltopdf:${WKHTMLTOPDF_VERSION}
  - export KWKHTMLTOPDF_SERVER_URL=http://localhost:8080

script:
  - tox

after_script:
  - docker logs kwkhtmltopdf
  - docker stop kwkhtmltopdf

jobs:
  include:
    - stage: test
      env:
        - WKHTMLTOPDF_VERSION=0.12.5
    - stage: deploy
      env:
        - WKHTMLTOPDF_VERSION=0.12.5
      deploy:
        provider: script
        script: bash travis/github_push
