FROM ubuntu:18.04

ENV PYTHONUNBUFFERED=1

RUN set -x \
  && apt update \
  && apt -y install --no-install-recommends wget ca-certificates \
  && wget -q -O /tmp/wkhtmltox.deb https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb \
  && echo "da820f2455da0e271cda6a724c9cf24ebdc96af3  /tmp/wkhtmltox.deb" | sha1sum -c - \
  && apt -y install /tmp/wkhtmltox.deb \
  && apt -y install --no-install-recommends python3-pip python3-setuptools \
  && apt -y purge wget --autoremove \
  && apt -y clean \
  && rm -rf /var/lib/apt/lists/*

COPY server/requirements.txt /tmp/
RUN pip3 install --no-cache -r /tmp/requirements.txt

COPY server/kwkhtmltopdf_server.py /usr/local/bin/

RUN adduser --disabled-password --gecos '' kwkhtmltopdf
USER kwkhtmltopdf
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

EXPOSE 8080
CMD /usr/local/bin/kwkhtmltopdf_server.py
