#!/bin/bash
echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io --username "${GITHUB_PACKAGE_USER}" --password-stdin
BUILD_NAME=${WKHTMLTOPDF_VERSION}-${TRAVIS_BUILD_NUMBER}
docker tag kwkhtmltopdf:${WKHTMLTOPDF_VERSION} ghcr.io/camptocamp/kwkhtmltopdf:${BUILD_NAME}

docker push camptocamp/kwkhtmltopdf

