name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 0"

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - "0.12.1.3"
          - "0.12.5"
          - "0.12.6.1"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.tag }}-latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
          file: Dockerfile-${{ matrix.tag }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ matrix.tag }}-latest
          cache-to: type=inline
          push: true
