name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        WKHTMLTOPDF_VERSION:
          - "0.12.1.3"
          - "0.12.5"
          - "0.12.6.1"
          # - "0.12.6.2" # TODO: not available yet
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          pip install tox
          sudo apt-get update
          sudo apt-get -y install -f ghostscript python3-requests
          # overwrite default imagemagick policy that prevents reading PDF
          sudo cp tests/travis-imagemagick-policy.xml /etc/ImageMagick-6/policy.xml
      - name: Install kwkhtmltopdf for local tests
        run: |
          wget -q -O /tmp/wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo apt -y install -f /tmp/wkhtmltox.deb
          rm -f /tmp/wkhtmltox.deb
      - name: Build and start server image
        run: |
          docker build -f Dockerfile-${{ matrix.WKHTMLTOPDF_VERSION }} -t kwkhtmltopdf:${{ matrix.WKHTMLTOPDF_VERSION }} .
          NAME=kwkhtmltopdf-${{ matrix.WKHTMLTOPDF_VERSION }}
          docker run -d --name "$NAME" -p 0:8080 kwkhtmltopdf:${{ matrix.WKHTMLTOPDF_VERSION }}
          PORT=$(docker port "$NAME" 8080/tcp | head -n 1 | sed 's/.*://')
          echo "KWK_CONTAINER_NAME=$NAME" >> "$GITHUB_ENV"
          echo "KWKHTMLTOPDF_SERVER_URL=http://localhost:$PORT" >> "$GITHUB_ENV"
      - name: Run tests
        run: WKHTMLTOPDF_VERSION=${{ matrix.WKHTMLTOPDF_VERSION }} tox

      - name: Cleanup
        run: |
          docker rm -f "$KWK_CONTAINER_NAME" || true
